### ISSUE TITLE
Stopped working since spotify 1.1.84.716

### ISSUE THREAD

**Issue by Maryse47** [mahkoh/spotblock#10]
For latest spotify release (1.1.84.716) the ads are no longer muted. Does anyone have idea if this can be fixed?

**Comment by parth-io** [comment]
I get this error message:
```
unable to process dbus message: exit_container failed: Device or resource busy
```

The error gets thrown in line 266 of `deamon.cc`, when `exit_container()` from `dbus.cc` gets called. I'm trying to understand what causes this issue and how DBus works first, my understanding of DBus is limited.

If you installed via snap, it's possible to revert to the earlier version by running:
```
$ snap list spotify  --all #to check if you have an earlier version
$ sudo snap revert spotify #to revert
```

**Comment by mahkoh** [comment]
Please try the current master

**Comment by Maryse47** [comment]
Works perfectly, thank you very much!
