### ISSUE TITLE
Doesn't support Pipewire

### ISSUE THREAD

**Issue by bluskript** [mahkoh/spotblock#9]
Pipewire is a more robust alternative to PulseAudio, however they are mutually exclusive so it is impossible to run this script when using Pipewire.

**Comment by mahkoh** [comment]
I haven't been using this program for multiple years but I don't see why it wouldn't work with pipewire as pipewire exposes a pulseaudio compatible interface.

**Comment by mahkoh** [comment]
I've confirmed that it also works with pipewire.
